export const FONT_SIZE = {
  TITLE2: 35.2,
  TITLE1: 28.1,
  SMALL_TITLE1: 22,
  SMALL_TITLE2: 18,
  SMALL_TITLE3: 14,
  BODY4: 22.5,
};

export const FONT_WEIGHT = {
  REGULAR: 400,
  MEDIUM: 500,
  SEMIBOLD: 600,
  BOLD: 700,
};

export const LINE_HEIGHT = {
  BODY: 40,
  TITLE: 30,
};

export const VERTICAL_MARGIN = {
  DEFAULT: LINE_HEIGHT.BODY,
  DOUBLE: LINE_HEIGHT.BODY * 2,
  HALF: LINE_HEIGHT.BODY / 2,
};
